variables:
    FDO_UPSTREAM_REPO:  'xorg/driver/xf86-input-mouse'
    DEBIAN_SKIP:        'true'

include:
    - local:    '.gitlab-ci/common/xorg-driver.yml'

build@freebsd:
    extends:
        - .xorg_driver_matrix@freebsd
        - .xorg_driver_common@freebsd
